### ISSUE TITLE
Jellyfin 10.9 - "Not Supported" with v3.2

### ISSUE THREAD

**Issue by Cebrain** [vosmiic/jellyfin-ani-sync#127]
**Describe the bug**
Version 3.2 is not working for me with 10.9
I dont know if it is related, but i use AniList and experience the same problem in the logs with latest version.

**Logs**

```
[2024-05-14 09:54:39.242 +02:00] [INF] [220] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[2024-05-14 09:54:39.246 +02:00] [ERR] [220] Emby.Server.Implementations.Plugins.PluginManager: Failed to load assembly "/config/plugins/Ani-Sync_3.2.0.0/jellyfin-ani-sync.dll". This error occurs when a plugin references an incompatible version of one of the shared libraries. Disabling plugin
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load file or assembly 'MediaBrowser.Common, Version=10.9.1.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

Could not load file or assembly 'MediaBrowser.Controller, Version=10.9.1.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

Could not load file or assembly 'MediaBrowser.Model, Version=10.9.1.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

Could not load file or assembly 'MediaBrowser.Model, Version=10.9.1.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

Could not load file or assembly 'Jellyfin.Data, Version=10.9.1.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

Could not load file or assembly 'MediaBrowser.Controller, Version=10.9.1.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

Could not load file or assembly 'MediaBrowser.Controller, Version=10.9.1.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

Could not load file or assembly 'MediaBrowser.Controller, Version=10.9.1.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

Could not load file or assembly 'MediaBrowser.Controller, Version=10.9.1.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

Could not load file or assembly 'MediaBrowser.Controller, Version=10.9.1.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at Emby.Server.Implementations.Plugins.PluginManager.LoadAssemblies()+MoveNext()
System.IO.FileNotFoundException: Could not load file or assembly 'MediaBrowser.Common, Version=10.9.1.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

File name: 'MediaBrowser.Common, Version=10.9.1.0, Culture=neutral, PublicKeyToken=null'
System.IO.FileNotFoundException: Could not load file or assembly 'MediaBrowser.Controller, Version=10.9.1.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

File name: 'MediaBrowser.Controller, Version=10.9.1.0, Culture=neutral, PublicKeyToken=null'
System.IO.FileNotFoundException: Could not load file or assembly 'MediaBrowser.Model, Version=10.9.1.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

File name: 'MediaBrowser.Model, Version=10.9.1.0, Culture=neutral, PublicKeyToken=null'
System.IO.FileNotFoundException: Could not load file or assembly 'MediaBrowser.Model, Version=10.9.1.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

File name: 'MediaBrowser.Model, Version=10.9.1.0, Culture=neutral, PublicKeyToken=null'
System.IO.FileNotFoundException: Could not load file or assembly 'Jellyfin.Data, Version=10.9.1.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

File name: 'Jellyfin.Data, Version=10.9.1.0, Culture=neutral, PublicKeyToken=null'
System.IO.FileNotFoundException: Could not load file or assembly 'MediaBrowser.Controller, Version=10.9.1.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

File name: 'MediaBrowser.Controller, Version=10.9.1.0, Culture=neutral, PublicKeyToken=null'
System.IO.FileNotFoundException: Could not load file or assembly 'MediaBrowser.Controller, Version=10.9.1.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

File name: 'MediaBrowser.Controller, Version=10.9.1.0, Culture=neutral, PublicKeyToken=null'
System.IO.FileNotFoundException: Could not load file or assembly 'MediaBrowser.Controller, Version=10.9.1.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

File name: 'MediaBrowser.Controller, Version=10.9.1.0, Culture=neutral, PublicKeyToken=null'
System.IO.FileNotFoundException: Could not load file or assembly 'MediaBrowser.Controller, Version=10.9.1.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

File name: 'MediaBrowser.Controller, Version=10.9.1.0, Culture=neutral, PublicKeyToken=null'
System.IO.FileNotFoundException: Could not load file or assembly 'MediaBrowser.Controller, Version=10.9.1.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

File name: 'MediaBrowser.Controller, Version=10.9.1.0, Culture=neutral, PublicKeyToken=null'
```

**To Reproduce**
Did try to reinstall the pugin, Uninstall -> Reboot -> Install -> Reboot 
Still the same

**Desktop (please complete the following information):**
 - Browser [firefox]
 - Jellyfin version [10.9]
 - Plugin version [3.2]

**Comment by vosmiic** [comment]
I think this may be an isolated issue, to confirm its not an issue with the plugin what version of the AniList plugin have you got installed? I am running version 9.0 on Jellyfin version 10.9.1 and I am running into no issues

**Comment by Cebrain** [comment]
The funny thing is AniList v8.0 is working but after upgrading to 9.0 it is not supported.
I will update Jellyfin to 10.9.1 maybe this fixes something (didnt know it is already out)
