### ISSUE TITLE
Manual sync to update provider with Jellyfin progress fails

### ISSUE THREAD

**Issue by Kapyyyy** [vosmiic/jellyfin-ani-sync#161]
**Describe the bug**
Doing a manual sync to provider fails

**Logs**
[2024-11-07 17:27:24.798 +00:00] [INF] [71] jellyfin_ani_sync.SyncProviderFromLocal: (Sync) Starting sync to provider from local process
[2024-11-07 17:27:24.798 +00:00] [INF] [71] jellyfin_ani_sync.SyncProviderFromLocal: (Sync) Retrieved SPY x FAMILY's seasons latest watched episode and when it was watched...
[2024-11-07 17:27:24.803 +00:00] [INF] [71] jellyfin_ani_sync.SyncProviderFromLocal: (Sync) Getting SPY x FAMILY seasons latest watched episode
[2024-11-07 17:27:24.804 +00:00] [INF] [71] jellyfin_ani_sync.SyncProviderFromLocal: (Sync) Series SPY x FAMILY contains 2 seasons
[2024-11-07 17:27:24.804 +00:00] [INF] [71] jellyfin_ani_sync.SyncProviderFromLocal: (Sync) Getting user data for Season 2 of SPY x FAMILY...
[2024-11-07 17:27:24.805 +00:00] [INF] [71] jellyfin_ani_sync.SyncProviderFromLocal: (Sync) Season contains 12 episodes
[2024-11-07 17:27:24.805 +00:00] [ERR] [71] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request. URL "POST" "/AniSync/sync".
System.MissingMethodException: Method not found: 'MediaBrowser.Controller.Entities.UserItemData MediaBrowser.Controller.Library.IUserDataManager.GetUserData(System.Guid, MediaBrowser.Controller.Entities.BaseItem)'.
   at jellyfin_ani_sync.SyncProviderFromLocal.<GetMaxEpisodeAndCompletedTime>b__16_2(Episode item)
   at System.Linq.Enumerable.WhereListIterator`1.ToList()
   at jellyfin_ani_sync.SyncProviderFromLocal.GetMaxEpisodeAndCompletedTime(Series series)
   at jellyfin_ani_sync.SyncProviderFromLocal.GetSeasonDetails(List`1 userSeriesList)
   at jellyfin_ani_sync.SyncProviderFromLocal.SyncFromLocal()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Jellyfin.Api.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Api.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Api.Middleware.IPBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Api.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Api.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Api.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Api.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Api.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Api.Middleware.ExceptionMiddleware.Invoke(HttpContext context)

**To Reproduce**
1. Go to Manual sync
2. Select "Update provider with Jellyfin progress"
3. Select which user and then click on run
4. See logs with error

**Expected behavior**
No errors, anime gets synced

**Desktop (please complete the following information):**
 - Browser latest version of brave on linux
 - Jellyfin version 10.10.0
 - Plugin version 3.4.0.0

**Additional info**
Testing user authentication works fine.

**Comment by vosmiic** [comment]
Thanks for reporting the bug, the [latest beta build](https://github.com/vosmiic/jellyfin-ani-sync/releases/tag/v3.6b) fixes this issue.

**Comment by Kapyyyy** [comment]
Hey, I manually installed the version you linked and now jellyfin is giving me an this alert: "This plugin has no settings to set up."
Did I do something wrong or could this be an another bug?

**Comment by vosmiic** [comment]
What is the status of the plugin? It should be "Active".
Also could you install it via the beta manifest? Instructions on how to do so are [here](https://github.com/vosmiic/jellyfin-ani-sync?tab=readme-ov-file#development).
