### ISSUE TITLE
Jellyfin docker crashing after exiting live tv.

### ISSUE THREAD

**Issue by samuraimarv** [vosmiic/jellyfin-ani-sync#47]
Installed plugin and confirmed it worked properly. When watching live tv from the account configured in the plugin to sync to MyAniList Jellyfin will crash after existing live tv. I've looked through the logs but can't find anything that stands out besides this Unhandled Exception from right before it crashes. This is me hitting the back button to exist live tv, this also does not happen on any other user that is not configured to use the plugin.

`[17:09:39] [INF] [27] Emby.Server.Implementations.LiveTv.TunerHosts.HdHomerun.HdHomerunHost: Copying of SharedHttpStream to /transcode/e925f8a2fec343b3a56c8a7c531b4b75.ts was canceled
[17:09:39] [INF] [27] Emby.Server.Implementations.LiveTv.TunerHosts.HdHomerun.HdHomerunHost: Deleting temp file /transcode/e925f8a2fec343b3a56c8a7c531b4b75.ts
[17:09:39] [WRN] [28] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from http://10.0.0.7:8096/Sessions/Playing/Stopped to 10.0.0.151 in 0:00:01.7494628 with Status Code 204
[17:09:39] [INF] [25] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Playback stop tracker found, processing stop : TW96aWxsYS81LjAgKE1hY2ludG9zaDsgSW50ZWwgTWFjIE9TIFggMTBfMTVfNykgQXBwbGVXZWJLaXQvNjA1LjEuMTUgKEtIVE1MLCBsaWtlIEdlY2tvKSBWZXJzaW9uLzE2LjIgU2FmYXJpLzYwNS4xLjE1fDE2NzIzNjQ2MzMwMjM1-41e7f311fe944026b4e80dacbcb61a07-cda10c0a8b5c53725d0bb3aa3716cb2f
[17:09:39] [INF] [25] Jellyfin.Plugin.PlaybackReporting.Data.PlaybackTracker: PlaybackTracker : Adding Stop Event : 12/31/2022 17:09:39
[17:09:39] [INF] [25] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Playback stop but TrackedPlaybackInfo not found! not storing activity in DB
[17:09:39] [FTL] [27] Main: Unhandled Exception
System.ArgumentNullException: Value cannot be null. (Parameter 'path')
   at Emby.Server.Implementations.IO.ManagedFileSystem.ContainsSubPath(String parentPath, String path)
   at jellyfin_ani_sync.UpdateProviderStatus.LibraryCheck(BaseItem item)
   at jellyfin_ani_sync.UpdateProviderStatus.Update(BaseItem e, Guid userId, Boolean playedToCompletion)
   at jellyfin_ani_sync.SessionServerEntry.PlaybackStopped(Object sender, PlaybackStopEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
`

I'm not sure what I'm missing here and any help would be greatly appreciated.

**Comment by vosmiic** [comment]
Hi, thanks for including the server logs. 
I have found the area that the bug is occurring, basically the plugin attempts to find the local file location of the media being played to check if it has been excluded from the "libraries to check" options. 
Obviously a live stream does not have a local file location, so it returns `null` for the location which the plugin does not like.
Partially my fault and the Jellyfin API's documentation fault since it does state that a base items path cannot be `null`, I'll push out a fix for this tomorrow (its quite late for me) and let you know when you can update your plugin which contains the fix.

**Comment by samuraimarv** [comment]
Awesome thanks so much for your quick reply.

**Comment by vosmiic** [comment]
>Awesome thanks so much for your quick reply.

No problem, the [new version](https://github.com/vosmiic/jellyfin-ani-sync/releases/tag/v2.6) of the plugin has now been released. If you have installed the plugin via the catalog, running the "Update Plugins" scheduled job and then restarting the Jellyfin server should update your local version to the latest.
I don't actually view live media so I haven't been able to test it, but as far as I can tell it should now no longer hit into the issue you were seeing. 
If the new version still does not fix the issue, please do let me know.
Thanks

**Comment by samuraimarv** [comment]
Just installed it and can confirm the update fixed the crashing issue, thanks again!
