### ISSUE TITLE
authentication fail

### ISSUE THREAD

**Issue by birdboytoy** [vosmiic/jellyfin-ani-sync#50]
i cant authenticate and i dont really understand why im very confused

**Comment by vosmiic** [comment]
What step are you up to?
What provider are you attempting to authenticate with?
Did you read the [guide](https://github.com/vosmiic/jellyfin-ani-sync/wiki)?
Do you have any errors in the Jellyfin logs related to this plugin?
I can't really help with such limited information, the authentication process could be failing at multiple points.

**Comment by birdboytoy** [comment]
It's for the token so I can sync my anilist data when I watch sum I authorized my user then tried the link didn't work then tried authorizimg again then restarted the server then did the link but kept giving me error even I copied the link into the search bar for the anilist provider

**Comment by vosmiic** [comment]
When navigating to the generated link did it simply not load or did it return an error?
I would confirm that you entered the correct client ID and secret, as they are necessary to generate a correct link

**Comment by birdboytoy** [comment]
this is wat it gives me 
![Screenshot 2023-01-07 205400](https://user-images.githubusercontent.com/85974426/211178419-81cc53cd-3025-4b1f-b10b-9684bceef050.png)

**Comment by vosmiic** [comment]
Okay, this means that the client ID is probably incorrect. I would make sure that there are no trailing spaces in the value entered.
I would also confirm that you have entered the correct redirect URL during the AniList app setup, as this can also cause issues later on during authentication.

**Comment by birdboytoy** [comment]
ok i tried it today im very lost on alot of this is there any video or ideo tutorial on this or i can share my screen for help

**Comment by vosmiic** [comment]
There aren't any video tutorials, at least on how to use the plugin, could you share the URL that is generated (please hide/change your client ID, and you can hide the base URL/redirect URL if you want. I only need to see the general structure of the URL e.g. `https://anilist.co/api/v2/oauth/authorize?response_type=code&client_id=1234&redirect_uri=https://mycallbackurl.com`) so I can see where the authentication process is failing

**Comment by FabrizioMFE** [comment]
@vosmiic having the same issue here's the generated structure 
`https://anilist.co/api/v2/oauth/authorize?response_type=code&client_id=12345&redirect_uri=http://localhost:8096/AniSync/authCallback
`
from what I searched in the Anilist API docs, it should be correct so this could be an issue on their side maybe?

**Comment by vosmiic** [comment]
I have just tested it locally and I was able to authenticate my user, so it probably isn't their end.
I would also make sure that the redirect URI matches the one you have entered in the AniList app, you will also get this error if they are not the same.

**Comment by FabrizioMFE** [comment]
Ok I figured out the problem 🤦 I forgot the rest of the URL at the end in the Anilist site, I had only put `http://localhost:8096/` when it should've been `http://localhost:8096/AniSync/authCallback` thanks and sorry about that 😅 

Only problem now is, after authorizing it responds with the code but it leaves me in a blank page, and while testing the authorization does work since it says my username, it doesn't save the changes, it keeps going back to MyAnimeList.

**Comment by vosmiic** [comment]
A blank page is normal, you can just close it.
Displaying the client ID and secret can be a little buggy  on the config page, if you tested the authentication and it responded with your AniList username it should be working.
Does the appropriate shows progress update in AniList if you try watching something? It's really the only sure fire way of knowing if the authentication worked or not.

**Comment by Kuuchuu** [comment]
@vosmiic I'm also having an error with testing the authentication, and when attempting to run a manual sync I get the error `[2023-02-02 20:30:31.524 -06:00] [WRN] The user ********************************** is not authenticated. Skipping`

Here is the error when clicking "Test Authentication"
```
[2023-02-02 20:35:02.229 -06:00] [ERR] Error processing request. URL "GET" "/AniSync/user".
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at jellyfin_ani_sync.Api.AuthApiCall.AuthenticatedApiCall(ApiName provider, CallType callType, String url, FormUrlEncodedContent formUrlEncodedContent, StringContent stringContent)
   at jellyfin_ani_sync.Helpers.GraphQlHelper.AuthenticatedRequest(IHttpClientFactory httpClientFactory, ILoggerFactory loggerFactory, IServerApplicationHost serverApplicationHost, IHttpContextAccessor httpContextAccessor, UserConfig userConfig, String query, ApiName provider, Dictionary`2 variables)
   at jellyfin_ani_sync.Api.Anilist.AniListApiCalls.GetCurrentUser()
   at jellyfin_ani_sync.Api.AniSyncController.GetUser(ApiName apiName, String userId)
   at lambda_method698(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)

```
After clicking "Authorize user" I get this as a response: `https://anilist.co/api/v2/oauth/authorize?response_type=code&client_id=*****&redirect_uri=https://*****.stream/AniSync/authCallback`

I have tried with both a MAL client/secret & an Anilist client/secret. Any help would be greatly appreciated.

**Comment by vosmiic** [comment]
Do you get an error back when authenticating? To complete the authentication, you should see a blank page. 
I would make sure that the redirect URI matches the one in your app, also test the redirect URI by navigating to it and you should see a 400 error.
