### ISSUE TITLE
System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by KaiserBh** [vosmiic/jellyfin-ani-sync#66]
Crashes the server.

```prolog
[2023-05-01 13:31:46.153 +00:00] [INF] Playback stopped reported by app "Jellyfin Media Player" "1.9.1" playing "That Time I Got Reincarnated as a Slime the Movie: Scarlet Bond". Stopped at "6513889" ms
[2023-05-01 13:31:46.212 +00:00] [INF] (Anidb) Anime already has AniDb ID; no need to look it up
[2023-05-01 13:31:46.224 +00:00] [FTL] Unhandled Exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at jellyfin_ani_sync.Helpers.AnimeListHelpers.<>c__DisplayClass0_0.<GetAniDbId>b__0(AnimeListAnime anime)
   at System.Linq.Enumerable.WhereListIterator`1.ToList()
   at jellyfin_ani_sync.Helpers.AnimeListHelpers.GetAniDbId(ILogger logger, ILoggerFactory loggerFactory, IHttpClientFactory httpClientFactory, IApplicationPaths applicationPaths, Video video, Int32 episodeNumber, Int32 seasonNumber)
   at jellyfin_ani_sync.UpdateProviderStatus.Update(BaseItem e, Guid userId, Boolean playedToCompletion)
   at jellyfin_ani_sync.SessionServerEntry.PlaybackStopped(Object sender, PlaybackStopEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
[2023-05-01 13:33:00.423 +00:00] [INF] Jellyfin version: "10.8.8"
[2023-05-01 13:33:00.435 +00:00] [INF] Environment Variables: ["[JELLYFIN_DATA_DIR, /var/lib/jellyfin]", "[JELLYFIN_CONFIG_DIR, /etc/jellyfin]", "[JELLYFIN_RESTART_OPT, --restartpath=/usr/lib/jellyfin/restart.sh]", "[JELLYFIN_ADDITIONAL_OPTS, ]", "[JELLYFIN_USER, jellyfin]", "[JELLYFIN_CACHE_DIR, /var/cache/jellyfin]", "[JELLYFIN_ARGS, $JELLYFIN_WEB_OPT $JELLYFIN_RESTART_OPT $JELLYFIN_FFMPEG_OPT $JELLYFIN_SERVICE_OPT $JELLYFIN_NOWEBAPP_OPT $JELLFIN_ADDITIONAL_OPTS]", "[JELLYFIN_WEB_OPT, --webdir=/usr/share/jellyfin/web]", "[JELLYFIN_FFMPEG_OPT, --ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg]", "[JELLYFIN_LOG_DIR, /var/log/jellyfin]"]
[2023-05-01 13:33:00.437 +00:00] [INF] Arguments: ["/usr/lib/jellyfin/bin/jellyfin.dll", "--webdir=/usr/share/jellyfin/web", "--restartpath=/usr/lib/jellyfin/restart.sh", "--ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg"]
[2023-05-01 13:33:00.437 +00:00] [INF] Operating system: "Linux"
[2023-05-01 13:33:00.437 +00:00] [INF] Architecture: X64
[2023-05-01 13:33:00.437 +00:00] [INF] 64-Bit Process: True
[2023-05-01 13:33:00.437 +00:00] [INF] User Interactive: True
[2023-05-01 13:33:00.437 +00:00] [INF] Processor count: 16
[2023-05-01 13:33:00.437 +00:00] [INF] Program data path: "/var/lib/jellyfin"
[2023-05-01 13:33:00.437 +00:00] [INF] Web resources path: "/usr/share/jellyfin/web"
[2023-05-01 13:33:00.438 +00:00] [INF] Application directory: "/usr/lib/jellyfin/bin/"
[2023-05-01 13:33:00.528 +00:00] [INF] Setting cache path: "/var/cache/jellyfin"
[2023-05-01 13:33:00.564 +00:00] [INF] Loading assemblies
[2023-05-01 13:33:00.581 +00:00] [INF] Loaded assembly "jellyfin-ani-sync, Version=2.7.1.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/Ani-Sync_2.7.1.0/jellyfin-ani-sync.dll"
[2023-05-01 13:33:00.583 +00:00] [INF] Loaded assembly "Jellyfin.Plugin.AniDB, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/AniDB_7.0.0.0/Jellyfin.Plugin.AniDB.dll"
[2023-05-01 13:33:00.585 +00:00] [INF] Loaded assembly "Jellyfin.Plugin.AniList, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/AniList_5.0.0.0/Jellyfin.Plugin.AniList.dll"
[2023-05-01 13:33:00.585 +00:00] [INF] Loaded assembly "ConfusedPolarBear.Plugin.IntroSkipper, Version=0.1.7.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/Intro Skipper_0.1.7.0/ConfusedPolarBear.Plugin.IntroSkipper.dll"
[2023-05-01 13:33:00.587 +00:00] [INF] Loaded assembly "Jellyfin.Plugin.Tvdb, Version=9.0.0.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/TheTVDB_9.0.0.0/Jellyfin.Plugin.Tvdb.dll"
[2023-05-01 13:33:00.588 +00:00] [INF] Loaded assembly "TvDbSharper, Version=3.2.2.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/TheTVDB_9.0.0.0/TvDbSharper.dll"
[2023-05-01 13:33:00.640 +00:00] [INF] Defined LAN addresses : "[10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]"
[2023-05-01 13:33:00.640 +00:00] [INF] Defined LAN exclusions : "[]"
[2023-05-01 13:33:00.640 +00:00] [INF] Using LAN addresses: "[10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]"
[2023-05-01 13:33:00.644 +00:00] [INF] Using bind addresses: "[192.168.1.143/32]"
[2023-05-01 13:33:00.644 +00:00] [INF] Using bind exclusions: "[]"
[2023-05-01 13:33:02.150 +00:00] [INF] Loaded plugin: "Ani-Sync" "2.7.1.0"
[2023-05-01 13:33:02.151 +00:00] [INF] Loaded plugin: "AniDB" "7.0.0.0"
[2023-05-01 13:33:02.151 +00:00] [INF] Loaded plugin: "AniList" "5.0.0.0"
[2023-05-01 13:33:02.169 +00:00] [INF] Loaded plugin: "Intro Skipper" "0.1.7.0"
[2023-05-01 13:33:02.169 +00:00] [INF] Loaded plugin: "TheTVDB" "9.0.0.0"
[2023-05-01 13:33:02.169 +00:00] [INF] Loaded plugin: "TMDb" "10.8.8.0"
[2023-05-01 13:33:02.169 +00:00] [INF] Loaded plugin: "Studio Images" "10.8.8.0"
[2023-05-01 13:33:02.169 +00:00] [INF] Loaded plugin: "OMDb" "10.8.8.0"
[2023-05-01 13:33:02.170 +00:00] [INF] Loaded plugin: "MusicBrainz" "10.8.8.0"
[2023-05-01 13:33:02.170 +00:00] [INF] Loaded plugin: "AudioDB" "10.8.8.0"
```

I know I am not using the latest version but for some reason I can only see v2.7.1.0 from the repo.
![image](https://user-images.githubusercontent.com/41852205/235466770-f04a73e8-5462-4745-91c3-152653d53853.png)

Do I have to update it manually?

Thanks in advance

**Comment by vosmiic** [comment]
What version of Jellyfin are you running? If it is the latest (10.8.10), it should auto-update the plugin. If you can't update the server, you will have to manually update the plugin.

**Comment by KaiserBh** [comment]
> What version of Jellyfin are you running (your screenshot suggests 10.8.8)? If it is the latest (10.8.10), it should auto-update the plugin. If you can't update the server, you will have to manually update the plugin.

Thanks, updated jellyfin and plugin is updated as well now. I will close this for now if it still happening will reopen it.
