### ISSUE TITLE
myanimelist - Client authentication failed

### ISSUE THREAD

**Issue by Lunar808** [vosmiic/jellyfin-ani-sync#77]
Jellyfin server version 10.8.10 installed as a Docker Container,  on Ubuntu 24.04 - Using jellyfin inside my local network.

When going manually to the authentication link, a pop-up login requests a username and password, but not relevant info that I entered is working, username as client id and password as client secret. and my MAL username and password as well.
the response is from the POST request is:
`{"error":"invalid_client","message":"Client authentication failed"}`

The issue persists when trying to authenticate with anilist too.

First I tried the solution provided in #25 
But jellyfin-ani-sync.xml had no parsing issues like the issue one of the users mentioned, Client id and secret are properly written in the xml, as well in the plugin settings on the jellyfin dashboard with no spaces and such.

Issue #65   is also similar as the author of the issue is using docker as well.

My container and docker network as a whole, isn't behind any proxy like the one mentioned in this comment which solved this user problem:
`For my case, I was running JF within a Docker container alongside Nginx Proxy Manager (didn't expose any ports on the JF container) so I had to set the redirect URL as the IP address that the JF container had in the Docker network and got it to work.`

What I tried:
-configuring the API Redirect URL as the jellyfin container internal IP(172.18.x.x) and as the server local ip network(192.168.x.x)
-opened the jellyfin ports on my router and trying to use my external IP as the auth callback, hoping to bypass this issue. the jellyfin server works on the internet but it wasn't solved this way
-tried multiple providers in addition to myanimelist, same problem appears with all providers.
-checked and made sure all ports used by my containers, jellyfin included; are forwarded and accepts incoming and outgoing traffic.

This is the Exception in the logs after pressing test authentication:
[2023-09-08 15:44:31.222 +03:00] [ERR] [51] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL "GET" "/AniSync/user".
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at jellyfin_ani_sync.Api.AuthApiCall.AuthenticatedApiCall(ApiName provider, CallType callType, String url, FormUrlEncodedContent formUrlEncodedContent, StringContent stringContent)
   at jellyfin_ani_sync.Api.MalApiCalls.GetUserInformation()
   at jellyfin_ani_sync.Api.AniSyncController.GetUser(ApiName apiName, String userId)
   at lambda_method1223(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)

EDIT: Forgot to mention that the container image used is linuxserver/jellyfin and not jellyfin/jellyfin

**Comment by vosmiic** [comment]
Unfortunately I probably won't be able to help out that much with this issue as I run my own Jellyfin instance on bare metal, and have never installed it inside a container. 
That being said, hopefully I can send a few pointers that might help work out where the issue lies.
First off,  the issue where you are prompted to login to the website when navigating to the MAL authentication link usually means that either the client ID or redirect URL is incorrect. 
I would make sure that the client ID that is contained in the generated URL is correct, and does not have any spaces/symbols.
Secondly, if the client ID is correct, make sure you have set the correct redirect URL in the MAL app. An easy way to find your redirect URL if the plugin suggests the wrong URL, is to attempt to navigate to the Jellyfin instance followed by `/AniSync/authCallback`. If it is the correct URL, you should be greeted by a 400 stating "The code field is required.". This is the valid URL that should be set in the MAL app.
Hopefully this has given a few pointers on how to fix the issues you have hit into.

**Comment by Lunar808** [comment]
> Unfortunately I probably won't be able to help out that much with this issue as I run my own Jellyfin instance on bare metal, and have never installed it inside a container. That being said, hopefully I can send a few pointers that might help work out where the issue lies. First off, the issue where you are prompted to login to the website when navigating to the MAL authentication link usually means that either the client ID or redirect URL is incorrect. I would make sure that the client ID that is contained in the generated URL is correct, and does not have any spaces/symbols. Secondly, if the client ID is correct, make sure you have set the correct redirect URL in the MAL app. An easy way to find your redirect URL if the plugin suggests the wrong URL, is to attempt to navigate to the Jellyfin instance followed by `/AniSync/authCallback`. If it is the correct URL, you should be greeted by a 400 stating "The code field is required.". This is the valid URL that should be set in the MAL app. Hopefully this has given a few pointers on how to fix the issues you have hit into.

Thank you!
I'm pretty sure I tried a couple of times the points you mentioned, But I will try again nonetheless. I took the time to read other closed issues that loosely resembles my issue, and my attempts right now are pointing to the fact to my jellyfin instance is indeed contained in docker and not as a standalone service.
I'm also reviewing the source code at the same time to check if there's a difference that I could make, for example, the plugin compiled with regular jellyfin, and comparing it to the jellyfin service that is used by the official container, I don't expect much difference or even at all, But I'm really eager to check every relevant point that could be connected to this issueespecially seeing there are other docker users that had similar issues. Reason is, This plugin is the reason I choose to stick to jellyfin.
Thank you very much for your work on this project! your coding is really impressive and your comments you remarked in every function I saw so far is really helpful. 

I'm closing the Issue for now. 
Hopefully I will resolve this issue, and if it's something I find that can be resolved with the project itself and not locally, I will be sure to send a pull request once I figure it out.
